# Generated by Django 2.2 on 2021-07-14 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veryniceapp', '0002_auto_20210711_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
